{
  config,
  lib,
  pkgs,
  ...
}: let
  inherit (lib) concatMapStringsSep concatStringsSep mkEnableOption mkIf mkOption nameValuePair optionalString types;
  cfg = config.spott.zsh.pluginSet;

  pluginType = types.submodule {
    options = {
      name = mkOption {
        type = types.str;
        description = "Stable name used for this plugin under ZDOTDIR/plugins.";
      };

      src = mkOption {
        type = types.nullOr types.path;
        default = null;
        description = "Immutable plugin source. Null is allowed for an in-tree init snippet.";
      };

      fpath = mkOption {
        type = types.listOf types.str;
        default = [];
        description = "Directories relative to the plugin source to prepend to fpath.";
      };

      autoload = mkOption {
        type = types.listOf types.str;
        default = [];
        description = "Functions to autoload with autoload -Uz.";
      };

      initFiles = mkOption {
        type = types.listOf types.str;
        default = [];
        description = "Files relative to the plugin source to source in order.";
      };

      initBefore = mkOption {
        type = types.lines;
        default = "";
        description = "Explicit Zsh initialization run immediately before this plugin's files are sourced.";
      };

      initExtra = mkOption {
        type = types.lines;
        default = "";
        description = "Explicit Zsh initialization run immediately after this plugin's files are sourced.";
      };

      preloadFiles = mkOption {
        type = types.listOf types.str;
        default = [];
        description = "Plugin files to concatenate and zcompile before init; originals become stubs to avoid dynamic re-sourcing.";
      };
    };
  };

  sourcePlugins = builtins.filter (plugin: plugin.src != null) cfg.plugins;
  names = map (plugin: plugin.name) cfg.plugins;
  filesToCompile = plugin:
    lib.unique (plugin.initFiles ++ lib.optional (plugin.preloadFiles != []) ".spott-preload.zsh");
  safeRelativePath = path:
    builtins.match "[A-Za-z0-9._+/-]+" path != null
    && !lib.hasPrefix "/" path
    && !lib.hasInfix ".." path;

  preparedSource = plugin: let
    compileFiles = filesToCompile plugin;
  in
    if compileFiles == []
    then plugin.src
    else
      pkgs.runCommand "zsh-plugin-${plugin.name}" {} ''
        mkdir "$out"
        cp -R ${plugin.src}/. "$out"
        chmod -R u+w "$out"
        ${optionalString (plugin.preloadFiles != []) ''
          cat ${concatMapStringsSep " " (path: ''"$out/${path}"'') plugin.preloadFiles} > "$out/.spott-preload.zsh"
          ${concatMapStringsSep "\n" (path: ''
            printf '%s\n' '# Preloaded from .spott-preload.zsh.' > "$out/${path}"
          '') plugin.preloadFiles}
        ''}
        ${concatMapStringsSep "\n" (path: ''
          ${pkgs.zsh}/bin/zsh -fc 'zcompile -R "$1.zwc" "$1"' _ "$out/${path}"
        '') compileFiles}
        ${concatMapStringsSep "\n" (path: ''
          # Keep source fallbacks small. Zsh selects the sibling wordcode;
          # the PTY smoke test verifies that initialization still occurred.
          printf '%s\n' '# Definitions are in the sibling .zwc file.' > "$out/${path}"
        '') plugin.initFiles}
        ${optionalString (plugin.preloadFiles != []) ''
          printf '%s\n' '# Definitions are in .spott-preload.zsh.zwc.' > "$out/.spott-preload.zsh"
        ''}
      '';

  fpathEntries = builtins.concatMap (
    plugin: map (path: "\"$_spott_zsh_plugin_root/${plugin.name}/${path}\"") plugin.fpath
  ) cfg.plugins;
  autoloads = builtins.concatMap (plugin: plugin.autoload) cfg.plugins;

  initFor = plugin:
    concatStringsSep "\n" (
      lib.optional (plugin.initBefore != "") plugin.initBefore
      ++ lib.optional (plugin.preloadFiles != []) "source \"\${\${:-\$_spott_zsh_plugin_root/${plugin.name}}:A}/.spott-preload.zsh\""
      ++ (map (path: "source \"\${\${:-\$_spott_zsh_plugin_root/${plugin.name}}:A}/${path}\"") plugin.initFiles)
      ++ lib.optional (plugin.initExtra != "") plugin.initExtra
    );

  sourceLinks = map (plugin:
    nameValuePair "zsh/plugins/${plugin.name}" {
      source = preparedSource plugin;
    }) sourcePlugins;

  preloadSupportLinks = builtins.concatMap (plugin:
    map (path:
      nameValuePair "zsh/plugin-support/${plugin.name}/${path}" {
        source = "${preparedSource plugin}/${path}";
      }) plugin.preloadFiles) sourcePlugins;

  loader = ''
    # Generated by the repository-local spott.zsh.pluginSet Home Manager module.
    # Plugin revisions are owned by flake.lock; this file performs no updates.
    typeset -g _spott_zsh_plugin_root="$ZDOTDIR/plugins"

    fpath=(
      ${concatStringsSep "\n  " fpathEntries}
      ''${fpath}
    )
    ${optionalString (autoloads != []) "autoload -Uz -- ${concatStringsSep " " autoloads}"}

    ${concatMapStringsSep "\n" initFor cfg.plugins}

    unset _spott_zsh_plugin_root
  '';
in {
  options.spott.zsh.pluginSet = {
    enable = mkEnableOption "the repository-local declarative Zsh plugin set";

    plugins = mkOption {
      type = types.listOf pluginType;
      default = [];
      description = "Ordered Zsh plugin declarations.";
    };
  };

  config = mkIf cfg.enable {
    assertions = [
      {
        assertion = builtins.length names == builtins.length (lib.unique names);
        message = "spott.zsh.pluginSet plugin names must be unique";
      }
      {
        assertion = builtins.all (plugin: builtins.match "[A-Za-z0-9._+-]+" plugin.name != null) cfg.plugins;
        message = "spott.zsh.pluginSet plugin names may contain only letters, digits, dot, underscore, plus, and hyphen";
      }
      {
        assertion = builtins.all (plugin: plugin.src != null || (plugin.fpath == [] && plugin.initFiles == [] && plugin.preloadFiles == [])) cfg.plugins;
        message = "spott.zsh.pluginSet plugins without src cannot declare fpath, initFiles, or preloadFiles";
      }
      {
        assertion = builtins.all (plugin:
          builtins.all safeRelativePath (plugin.fpath ++ plugin.initFiles ++ plugin.preloadFiles)) cfg.plugins;
        message = "spott.zsh.pluginSet paths must be safe relative paths";
      }
    ];

    xdg.configFile =
      builtins.listToAttrs (sourceLinks ++ preloadSupportLinks)
      // {
        "zsh/plugin-loader.zsh".text = loader;
      };
  };
}
