# Set PATH, MANPATH, etc., for Homebrew.
if [ -e '/opt/homebrew/bin/brew' ]; then
  eval "$(/opt/homebrew/bin/brew shellenv)"
fi

# Nix Home Manager
if [ -e '/nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh' ]; then
  . '/nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh'
fi
# Nix-darwin home manager
if [ -e "/etc/profiles/per-user/$USER/etc/profile.d/hm-session-vars.sh" ]; then
  . "/etc/profiles/per-user/$USER/etc/profile.d/hm-session-vars.sh"
fi
# End Nix

# add VSCode to path:
export PATH="${PATH}:/Applications/Visual Studio Code.app/Contents/Resources/app/bin"

# Add local python to path
#export PATH="${PATH}:${HOME}/Library/Python/3.9/bin"

# Add .local/bin to path:
export PATH="${PATH}:${HOME}/.local/bin"

# For pipx, so python doesn't break on garbage collection:
export PIPX_DEFAULT_PYTHON="/etc/profiles/per-user/spott/bin/python3"

# poetry and helm config directories should be in the linux place:

export XDG_CONFIG_HOME="${HOME}/.config/"
export XDG_DATA_HOME="${HOME}/.local/"
export XDG_CACHE_HOME="${HOME}/.cache/"
export XDG_RUNTIME_DIR="${HOME}/Library/Caches/TemporaryItems/"

# export POETRY_CONFIG_DIR="${XDG_CONFIG_HOME}/pypoetry"
# export POETRY_DATA_DIR="${XDG_DATA_HOME}/pypoetry"

export HELM_CONFIG_HOME="${XDG_CONFIG_HOME}/helm"
export HELM_DATA_HOME="${XDG_DATA_HOME}/helm"
export HELM_CACHE_HOME="${XDG_CACHE_HOME}/helm"

